sudo: required

language: ruby

rvm:
  - 2.2.3

git:
  depth: 25

services:
  - docker

before_install:
  - docker build -t rmarchei/hpacucli .

script:
  - docker run --rm --privileged rmarchei/hpacucli version
